const vulakSignup = [
	{ name: '\u200B', value: '\u200B' },
	{ name: 'KITERS: 🏃‍♂️', value: '\u200B' },
	{ name: 'Zed', value: '--', inline: true },
	{ name: 'Dktan', value: '--', inline: true },
	{ name: 'Rlinf', value: '--', inline: true },
	{ name: 'Velcra', value: '--', inline: true },
	{ name: 'Degta', value: '--', inline: true },
	{ name: 'Sarek', value: '--', inline: true },
	{ name: 'Backup 1', value: '--', inline: true },
	{ name: 'Backup 2', value: '--', inline: true },
	{ name: 'Backup 3', value: '--', inline: true },
	{ name: '\u200B', value: '\u200B' },
	{ name: 'Mage DA\'s: 🌟', value: '\u200B' },
	{ name: 'Mage L-1', value: '--' },
	{ name: 'Mage L-2', value: '--' },
	{ name: 'Mage R-1', value: '--' },
	{ name: 'Mage R-2', value: '--' },
	{ name: '\u200B', value: '\u200B' },
	{ name: 'DISCIPLINES: ⚔', value: '\u200B' },
	{ name: 'Melee Disc 1', value: '--', inline: true },
	{ name: 'Melee Disc 2', value: '--', inline: true },
	{ name: 'Melee Disc 3', value: '--', inline: true },
	{ name: 'Melee Disc 4', value: '--', inline: true },
	{ name: 'Melee Disc 5', value: '--', inline: true },
	{ name: 'Melee Disc 6', value: '--', inline: true },
];

const ltkSignup = [
	{ name: '\u200B', value: '\u200B' },
	{ name: 'KITERS: <:wizepic:ID>', value: '\u200B' },
	{ name: 'East 1', value: '--', inline: true },
	{ name: 'East 2', value: '--', inline: true },
	{ name: 'East 3', value: '--', inline: true },
	{ name: '\u200B', value: '\u200B' },
	{ name: 'North 1', value: '--', inline: true },
	{ name: 'North 2', value: '--', inline: true },
	{ name: 'North 3', value: '--', inline: true },
	{ name: '\u200B', value: '\u200B' },
	{ name: 'South 1', value: '--', inline: true },
	{ name: 'South 2', value: '--', inline: true },
	{ name: 'South 3', value: '--', inline: true },
	{ name: '\u200B', value: '\u200B' },
	{ name: 'DISCIPLINE: <:monkepic:ID>', value: '\u200B' },
	{ name: 'Discipline', value: '--' },
	{ name: '\u200B', value: '\u200B' },
];

exports.vulakSignup = vulakSignup;
exports.ltkSignup = ltkSignup;